### ISSUE TITLE
META: Roadmap for feature enhancements of this module

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ip#13]
Some thoughts about possible improvements to this module. Comments and feedback solicited.

- [ ] **Add a configuration setting to allow recording of local IP addresses.** This can be useful for development and testing of this module on a local site. Currently, local IP addresses (e.g., "::1") are ignored.
- [ ] **Instead of `_ip_demasquerade()`, consider adding a `hook_something_alter(&$account)` API**  and then performing the demasquerading in an implementation of that hook.
- [ ] **Handle deleting of nodes and comments.** Delete the corresponding entries from the `ip_posts` table.
- [ ] **Add ability to display IP addresses for node and comment creators.** This information is recorded in the `ip_posts` table, but not currently displayed anywhere. Perhaps a new tab on the node page. Add next to posting name on comments? Add config options to turn on/off this display. Add an admin page for node and comment IP addresses?
- [ ] **Add Bulk Operations ability to remove `ip_posts` records from admin page.** This will entail making `ip_post` entries an Entity, like we've done for `ip_tracker` entries.
- [ ] **Add `bee` commands equivalent to the existing `drush` commands.**
